# This is
#  - compiling all connectors
#  - running core tests
#
# I would prefer to run tests for the connectors, but mysql service start fails as of this writing:
#
#services:
#  - mysql
#
#  yields in logs:
#  Starting MySQL 5.7
#  Start-Service : Cannot find any service with service name 'MySQL57'.
#
#
# To be continued ...

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"

os:
  - Visual Studio 2022

platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

install:
  - vcpkg install sqlite3:x64-windows

cache:
  - c:\tools\vcpkg\installed\

build_script:
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS="/EHsc /std:c++latest" %CMAKE_TOOLCHAIN_FILE% -DBUILD_MYSQL_CONNECTOR=ON -DBUILD_POSTGRESQL_CONNECTOR=ON -DBUILD_SQLITE3_CONNECTOR=ON
  - cmake --build . --config %configuration%
  - cd tests
  - cd core
  - ctest . --build-config %configuration%
