os:
  - Visual Studio 2022

platform:
  - x64

services:
  - mysql

configuration:
  - Release

matrix:
  fast_finish: true

build_script:
  - CD
  - echo %configuration%
  #- SET PATH=%PATH%;C:\Program Files\MySQL\MySQL Server 5.7\bin
  #- set MYSQL_PWD=Password12!
  #- mysql -e "create database sqlpp_mysql;" --user=root
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /std:c++latest" -DBUILD_MYSQL_CONNECTOR=ON
  - cmake --build .
  #- ctest --output-on-failure
